[package]
name = "gir"
version = "0.1.0"
edition = "2024"

[dependencies]
byteorder = "1.5.0"
clap = { version = "4.5.48", features = ["derive"] }
flate2 = "1.1.2"
hex = "0.4.3"
sha1 = "0.10.6"
walkdir = "2.5.0"
